# Minimal picom config for bspwm

backend = "xrender";
vsync = true;

inactive-opacity = 0.82;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

fading = true;
fade-delta = 3;
fade-in-step = 0.03;
fade-out-step = 0.03;

shadow = false;
blur-method = "none";

opacity-rule = [
    "100:class_g = 'dmenu'",
    "100:class_g = 'Rofi'"
];
